[2024-07-04T09:15:56.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T09:15:56.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_pipeline.Extraction manual__2024-07-04T09:15:52.534200+00:00 [queued]>
[2024-07-04T09:15:56.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_pipeline.Extraction manual__2024-07-04T09:15:52.534200+00:00 [queued]>
[2024-07-04T09:15:56.236+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-04T09:15:56.255+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): Extraction> on 2024-07-04 09:15:52.534200+00:00
[2024-07-04T09:15:56.270+0000] {standard_task_runner.py:63} INFO - Started process 100 to run task
[2024-07-04T09:15:56.277+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_pipeline', 'Extraction', 'manual__2024-07-04T09:15:52.534200+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmplgl5e7e1']
[2024-07-04T09:15:56.278+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask Extraction
[2024-07-04T09:15:56.340+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_pipeline.Extraction manual__2024-07-04T09:15:52.534200+00:00 [running]> on host b272c9768427
[2024-07-04T09:15:56.433+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_pipeline' AIRFLOW_CTX_TASK_ID='Extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T09:15:52.534200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-04T09:15:52.534200+00:00'
[2024-07-04T09:15:56.434+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T09:15:56.435+0000] {extract.py:63} INFO - Starting news extraction process
[2024-07-04T09:15:57.086+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T09:15:57.087+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract.py", line 121, in extract
    p.set_options(p.OPT.MENTION, p.OPT.EMOJI, p.OPT.HASHTAG, p.OPT.RESERVED, p.OPT.SMILEY, p.OPT.URL)
    ^^^^^^^^^^^^^
AttributeError: module 'preprocessor' has no attribute 'set_options'
[2024-07-04T09:15:57.101+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_pipeline, task_id=Extraction, run_id=manual__2024-07-04T09:15:52.534200+00:00, execution_date=20240704T091552, start_date=20240704T091556, end_date=20240704T091557
[2024-07-04T09:15:57.115+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task Extraction (module 'preprocessor' has no attribute 'set_options'; 100)
[2024-07-04T09:15:57.134+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T09:15:57.161+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T09:15:57.166+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
